### ISSUE TITLE
Cannot Access Builder on Fresh Install

### ISSUE THREAD

**Issue by buff0k** [frappe/builder#172]
Using Bench production (v15) with a new site, can install builder but not access via web interface, following error is displayed in browser:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/path_resolver.py", line 44, in resolve
    endpoint = frappe.get_attr(handler)(self.path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 592, in resolve_path
    [Rule(f"/{d.route}", endpoint=d.name) for d in get_web_pages_with_dynamic_routes()],
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/caching.py", line 156, in redis_cache_wrapper
    val = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 580, in get_web_pages_with_dynamic_routes
    return frappe.get_all(
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2057, in get_all
    return get_list(doctype, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2032, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 185, in execute
    self.columns = self.get_table_columns()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 546, in get_table_columns
    return get_table_columns(self.doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/meta.py", line 73, in get_table_columns
    return frappe.db.get_table_columns(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 1197, in get_table_columns
    raise self.TableMissingError("DocType", doctype)
pymysql.err.ProgrammingError: ('DocType', 'Builder Page')

**Comment by surajshetty3416** [comment]
```bash
bench --site <your-site-name> migrate
```
maybe run this command from your bench and try again?
