### ISSUE TITLE
App fails to build while bench get-app

### ISSUE THREAD

**Issue by yigitkeremoktay** [frappe/builder#25]
Hello,

I'm attempting to install builder into an erpnext environment running inside docker coompose. When I run bench get-app builder inside the backend container, the below error occurs during the yarn build command:

        `Running build command for builder
        $ cd frontend && yarn build
        $ vite build --base=/assets/builder/frontend/ && yarn copy-html-entry
        ✘ [ERROR] No matching export in "../../../sites/common_site_config.json" for import "webserver_port"
        
            vite.config.js:4:9:
              4 │ import { webserver_port } from "../../../sites/common_site_config.j...
                ╵          ~~~~~~~~~~~~~~
        
        failed to load config from /home/frappe/frappe-bench/apps/builder/frontend/vite.config.js
        error during build:
        Error: Build failed with 1 error:
        vite.config.js:4:9: ERROR: No matching export in "../../../sites/common_site_config.json" for import "webserver_port"
            at failureErrorWithLog (/home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:1575:15)
            at /home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:1033:28
            at runOnEndCallbacks (/home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:1447:61)
            at buildResponseToResult (/home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:1031:7)
            at /home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:1143:14
            at responseCallbacks.<computed> (/home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:680:9)
            at handleIncomingPacket (/home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:735:9)
            at Socket.readFromStdout (/home/frappe/frappe-bench/apps/builder/node_modules/esbuild/lib/main.js:656:7)
            at Socket.emit (node:events:517:28)
            at addChunk (node:internal/streams/readable:335:12)
        error Command failed with exit code 1.
        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
        error Command failed with exit code 1.
        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
        Error: Command failed: yarn build
            at checkExecSyncError (node:child_process:890:11)
            at execSync (node:child_process:962:15)
            at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:451:5)
            at execute (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:128:23)
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
          status: 1,
          signal: null,
          output: [ null, null, null ],
          pid: 463,
          stdout: null,
          stderr: null
        }
        error Command failed with exit code 1.
        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
        Traceback (most recent call last):
          File "<frozen runpy>", line 198, in _run_module_as_main
          File "<frozen runpy>", line 88, in _run_code
          File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
            main()
          File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
            click.Group(commands=commands)(prog_name="bench")
          File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
            return self.main(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
            rv = self.invoke(ctx)
                 ^^^^^^^^^^^^^^^^
          File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
            return _process_result(sub_ctx.command.invoke(sub_ctx))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
            return _process_result(sub_ctx.command.invoke(sub_ctx))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
            return ctx.invoke(self.callback, **ctx.params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
            return __callback(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 72, in build
            bundle(
          File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 257, in bundle
            frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
          File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
            raise subprocess.CalledProcessError(return_, command)
        subprocess.CalledProcessError: Command 'yarn run production --apps builder --run-build-command' returned non-zero exit status 1.
        ERROR: bench build --app builder
        subprocess.CalledProcessError: Command 'bench build --app builder' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/usr/local/bin/bench", line 8, in <module>
            sys.exit(cli())
                     ^^^^^
          File "/usr/local/lib/python3.11/site-packages/bench/cli.py", line 132, in cli
            bench_command()
          File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", line 167, in get_app
            get_app(
          File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 444, in get_app
            app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
          File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 126, in wrapper_fn
            return fn(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^
          File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 242, in install
            install_app(
          File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 586, in install_app
            build_assets(bench_path=bench_path, app=app)
          File "/usr/local/lib/python3.11/site-packages/bench/utils/bench.py", line 351, in build_assets
            exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
          File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
            raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
        bench.exceptions.CommandFailedError: bench build --app builder`

**Comment by surajshetty3416** [comment]
@yigitkeremoktay Not sure how you have configured your docker installation. It'll help if you can share that part to investigate this further. 

But you can resolve this issue by placing "**common_site_config.json**" file inside your `sites` folder. Make sure to set "webserver_port" your actual in that file.

**Comment by yigitkeremoktay** [comment]
Hey, sorry for the late response, I was using the https://github.com/frappe/frappe_docker repo using its basic instructions. I figured out how to add that config value but what should the value be?
