### ISSUE TITLE
Error in data script - AttributeError: module has no attribute 'get_all'

### ISSUE THREAD

**Issue by maasanto** [frappe/builder#260]
Hey Suraj,

Thanks a lot for your excellent work on frappe builder. 
I am having an issue when trying to save a data script. It looks like the frappe database API aren't recognised in safer_exec.

My site is hosted on frappe cloud on a shared bench and runs the following apps:
- Frappe Framework 15.50.0
- Frappe Builder 1.12.5

Here is a simple data script to trigger the issue:
```
data.users = frappe.get_all("User")
```
An the error trace 

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1725, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 337, in run_doc_method
    response = doc.run_method(method, **args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 966, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1326, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1308, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 963, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 258, in get_page_data
    execute_script(self.page_data_script, _locals, self.name)
  File "apps/builder/builder/utils.py", line 275, in execute_script
    safer_exec(script, None, _locals, script_filename=script_filename)
  File "apps/builder/builder/utils.py", line 134, in safer_exec
    exec(
  File "<serverscript>: page_e2317a34", line 1, in <module>
  File "apps/frappe/frappe/utils/safe_exec.py", line 54, in default_function
    raise AttributeError(f"module has no attribute '{key}'")
AttributeError: module has no attribute 'get_all'
```

For the record I am having the same issue after enabling server_script and migrating my site. Here is my site_config:
```
{
  "server_script_enabled": 1
}
```

Cheers,
Antoine.

**Comment by maasanto** [comment]
Hey @surajshetty3416,

Actually `frappe.get_all` works (see below).
Enabling server script fixed it on my server but didn't on frappe cloud.
`bench --site {site} set-config server_script_enabled true`

![image](https://github.com/user-attachments/assets/4728f7ab-44be-4d0b-b20a-1d78c320f088)

**Comment by j2l** [comment]
I'm also evaluating frappe builder.
In my setup, I need `frappe.db.get_list(...)` as @surajshetty3416 mentioned.
But I noted that the "doc" in https://docs.frappe.io/builder/data-script states the `data.users = frappe.get_all("User")` way.
Is there a way to add loops and conditions based on the data script?
Builder doc is sparse :)

**Comment by batonac** [comment]
Check out the list of functions you can use here:

[def get_safe_globals():](https://github.com/frappe/frappe/blob/develop/frappe%2Futils%2Fsafe_exec.py#L168)

**Comment by j2l** [comment]
Thank you @batonac and happy new year!!

**Comment by Helkyd** [comment]
Hi all,
I have installed the below versions and enabled under site_config but still receive this error when adding any frappe function 
**VERSIONS:**
frappe                       15.53.0 version-15
erpnext                      15.49.3 version-15
builder                      1.14.1  master

SITE_CONFIG
**"server_script_enabled": true,**

**DATA SCRIPT**
data.events = frappe.db.get_list("Event",fields=["*"],filters = [["modified", ">", "2014-01-01"]],limit=30)
for event in data.events:
    event.mes_inicio = str(event.starts_on)[5:7]
    event.dia_inicio = str(event.starts_on)[8:10]
    event.ano_inicio = str(event.starts_on)[:4]
    event.anomesdia = frappe.format_date(event.starts_on)
    

**ERROR**
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 338, in run_doc_method
    response = doc.run_method(method, **args)
  File "apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 259, in get_page_data
    execute_script(self.page_data_script, _locals, self.name)
  File "apps/builder/builder/utils.py", line 275, in execute_script
    safer_exec(script, None, _locals, script_filename=script_filename)
  File "apps/builder/builder/utils.py", line 134, in safer_exec
    exec(
  File "<serverscript>: page_1bec994d", line 6, in <module>
  File "apps/frappe/frappe/utils/safe_exec.py", line 54, in default_function
    raise AttributeError(f"module has no attribute '{key}'")
AttributeError: module has no attribute 'format_date'
