### ISSUE TITLE
Unable to install in v15.

### ISSUE THREAD

**Issue by shahid03351206668** [frappe/builder#61]
```
Getting builder
$ git clone https://github.com/frappe/builder.git  --depth 1 --origin upstream
Cloning into 'builder'...
remote: Enumerating objects: 186, done.
remote: Counting objects: 100% (186/186), done.
remote: Compressing objects: 100% (169/169), done.
remote: Total 186 (delta 15), reused 98 (delta 6), pack-reused 0
Receiving objects: 100% (186/186), 250.43 KiB | 3.58 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Ignoring dependencies of https://github.com/frappe/builder.git. To install dependencies use --resolve-deps
Installing builder
$ /opt/bench/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /opt/bench/frappe-bench/apps/builder 

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python -m pip install --upgrade pip
$ yarn install
yarn install v1.22.21
(node:68737) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
(Use node --trace-deprecation ... to show where the warning was created)
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > builder-ui@0.0.0" has unmet peer dependency "ace-builds@^1.22.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/extension-color@2.0.4" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/extension-font-family@2.0.4" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/extension-link@2.1.12" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/extension-text-style@2.0.4" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/pm@2.0.4" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/vue-3@2.0.4" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/vue-3 > @tiptap/extension-bubble-menu@2.0.4" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > @tiptap/vue-3 > @tiptap/extension-floating-menu@2.0.4" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-highlight@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-image@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-link@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-mention@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-placeholder@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-table@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-table-cell@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-table-header@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-table-row@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-text-align@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/extension-typography@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "workspace-aggregator-29fd6d24-3d0d-41c9-979b-a99f036c6994 > builder-ui > frappe-ui > @tiptap/suggestion@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ cd frontend && yarn install
yarn install v1.22.21
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.64s.
Done in 41.37s.
$ bench build --app builder
Linking /opt/bench/frappe-bench/apps/frappe/node_modules to ./assets/frappe/node_modules                                                                        Linking /opt/bench/frappe-bench/apps/hrms/node_modules to ./assets/hrms/node_modules                                                                            Linking /opt/bench/frappe-bench/apps/builder/node_modules to ./assets/builder/node_modules                                                                      Linking /opt/bench/frappe-bench/apps/employee_self_service/employee_self_service/public to ./assets/employee_self_service                                       Linking /opt/bench/frappe-bench/apps/ikit_trading/ikit_trading/public to ./assets/ikit_trading                                                                  Linking /opt/bench/frappe-bench/apps/erpnext/node_modules to ./assets/erpnext/node_modules                                                                      ✔ Application Assets Linked                                            


yarn run v1.22.21
warning ../../../package.json: No license field
$ node esbuild --production --apps builder --run-build-command
File                                                        Size

 DONE  Total Build Time: 260.735ms


Running build command for builder
$ cd frontend && yarn build
$ vite build --base=/assets/builder/frontend/ && yarn copy-html-entry
vite v3.2.7 building for production...
transforming (98) src/pages/PagePreview.vueBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
transforming (173) ../node_modules/socket.io-client/build/esm/manager.js
                nter-DisplayRegular.woff2?v=3.19 referenced in /opt/bench/frappe-bench/apps/builder/frontend/src/index.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
transforming (495) ../node_modules/ace-builds/src-noconflict/ace.jsKilled
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at genericNodeError (node:internal/errors:956:15)
    at wrappedFn (node:internal/errors:510:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run_build_command_for_apps (/opt/bench/frappe-bench/apps/frappe/esbuild/esbuild.js:451:5)
    at execute (/opt/bench/frappe-bench/apps/frappe/esbuild/esbuild.js:128:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 137,
  signal: null,
  output: [ null, null, null ],
  pid: 68899,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/opt/bench/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in _call_
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bench/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/bench/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bench/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bench/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bench/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bench/frappe-bench/apps/frappe/frappe/commands/utils.py", line 72, in build
    bundle(
  File "/opt/bench/frappe-bench/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/commands/_init_.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps builder --run-build-command' returned non-zero exit status 1.
ERROR: bench build --app builder
subprocess.CalledProcessError: Command 'bench build --app builder' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/commands/make.py", line 167, in get_app
    get_app(
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 242, in install
    install_app(
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 586, in install_app
    build_assets(bench_path=bench_path, app=app)
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/bench.py", line 351, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/_init_.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench build --app builder
```

**Comment by surajshetty3416** [comment]
@shahid03351206668 I have not encountered this yet but on googling a bit I got to know that exit code 137 is related to insufficient memory. Please make sure you have enough memory during the build process.

---
Also, you can retry `bench build --app builder` and see if it works now?

**Comment by shahid03351206668** [comment]
@surajshetty3416 thanks for replying, i tried that but still not finishing, should i try to upgrade my RAM? right now its 2GB.

**Comment by surajshetty3416** [comment]
> should i try to upgrade my RAM?
@shahid03351206668 yep try it out it, might help

**Comment by shahid03351206668** [comment]
it worked by increasing the RAM, thanks.
