### ISSUE TITLE
Bug on page preview/publish

### ISSUE THREAD

**Issue by valdir-amaral** [frappe/builder#66]
I have this page, with a considerable number of components:

![image](https://github.com/frappe/builder/assets/109113918/73d317c0-7858-460c-97fa-88bd3e510cb8)

When i click on "preview" or "publish", it doesn't render and returns the following error:

```python
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 43, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 524, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 52, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 67, in update_context
    ret = self.doc.get_context(self.context)
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 125, in get_context
    content, style, fonts = get_block_html(blocks)
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 326, in get_block_html
    data = get_html(blocks, soup)
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 322, in get_html
    html += str(get_tag(block, soup))
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 315, in get_tag
    tag.append(get_tag(child, soup, data_key=data_key))
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 315, in get_tag
    tag.append(get_tag(child, soup, data_key=data_key))
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 315, in get_tag
    tag.append(get_tag(child, soup, data_key=data_key))
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 271, in get_tag
    append_state_style(state_styles, style_tag, style_class)
  File "apps/builder/builder/builder/doctype/builder_page/builder_page.py", line 359, in append_state_style
    state, property = key.split(":")
ValueError: too many values to unpack (expected 2)
```

I think it's because i copied and paste too many components, but all the properties are defined correctly

**Comment by surajshetty3416** [comment]
@valdir-amaral 

Hi, can check if any of your raw style's key have more than one ":"

I'll push the fix to handle it.

**Comment by valdir-amaral** [comment]
Worked perfectly! Thanks
