### ISSUE TITLE
frappe erpnext v13 No module named 'frappe.website.serve')

### ISSUE THREAD

**Issue by infoelectrofrio** [frappe/builder#8]
Hello, trying to install frappe builder on my frappe v13 gives me this error_:

An error occurred while installing website_builder: Module import failed for Builder Page (website_builder.website_builder.doctype.builder_page.builder_page Error: No module named 'frappe.website.serve')
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 238, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/website_builder/website_builder/website_builder/doctype/builder_page/builder_page.py", line 13, in <module>
    from frappe.website.serve import get_response_content, get_response
ModuleNotFoundError: No module named 'frappe.website.serve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 293, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 186, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 75, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 146, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 275, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 376, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 435, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 240, in load_doctype_module
    raise ImportError(
ImportError: Module import failed for Builder Page (website_builder.website_builder.doctype.builder_page.builder_page Error: No module named 'frappe.website.serve')

**Comment by mohsinalimat** [comment]
This app is not compatible with version-13 and version-14.

**Comment by surajshetty3416** [comment]
@infoelectrofrio The app is compatible with v14 and above.
